services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: Lain
      POSTGRES_PASSWORD: 1206
      POSTGRES_DB: filmsdb
    ports:
      - "5000:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
